### ISSUE TITLE
Unable to get report when multiple suites

### ISSUE THREAD

**Issue by Freyskeyd** [Vanare/behat-cucumber-formatter#12]
Hi,

i've this behat.yml:

``` yml
default:
  extensions:
    Vanare\BehatCucumberJsonFormatter\Extension:
      filename: report.json
      outputDir: %paths.base%/build
  suites:
    default:
      paths: [ %paths.base%/features/default ]
      contexts:
        - WebFeatureContext
    live:
      paths: [ %paths.base%/features/live ]
      contexts:
        - LiveContext
```

Then if i run this:

``` bash
behat -f cucumber_json features/default/google.feature
# reports.json -> []
behat -f cucumber_json features/live/something.feature
# reports.json -> [{...}]
```

if i comment live suite, then default suite are working fine.

Any idea?
